fyers:
  access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCcENSc29pM1NGdTUyQ29hLTN3cXBPVjRFQ0R1WVZET2plcjgxVTZaNGxsNnIwOFBpYlVfUkFYN1BYSEFQT0diVmdoalAzc2hkU01fYkxPOGtDMVQ3Z0EyNWVaalg5LWFWRnBtQ3JOOS1nel9mREVtRT0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI2MTZmMWEyZjJlZDY2ODhiZDVjNDA0Y2NjOTM2Y2ZhYTZjYWExODNjYmQ5ZTg1Y2IyMTk0MjdkNiIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWU0wNDA3NyIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzYyMzAyNjAwLCJpYXQiOjE3NjIyMDQ0NTYsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc2MjIwNDQ1Niwic3ViIjoiYWNjZXNzX3Rva2VuIn0.UC5bMUn_aU7UQtCG9PiKGMUzUiRF1AmF4_uu6d2YAQ0
  client_id: QZAWYQ69KZ-100
  redirect_uri: https://trade.fyers.in/api-login/redirect-uri/index.html
  secret_key: J02WG5J3V9
  token_expiry: '2025-11-05 10:14:16'
  totp_key: ''
logging:
  file: logs/strategy.log
  level: INFO
strategy:
  analysis_time: 09:20
  breakout_pct: 10
  max_holding_minutes: 30
  max_strike_distance: 500
  min_premium_threshold: 50.0
  partial_exits:
  - exit_percentage: 30
    min_profit_pct: 8
    time_minutes: 10
  - exit_percentage: 40
    min_profit_pct: 12
    time_minutes: 20
  risk_reward_ratio: 2
  stoploss_pct: 20
  symbol: NSE:NIFTY50-INDEX
  trailing_stop_pct: 8
  trailing_trigger_pct: 12
  use_trailing_stop: true
